use_frameworks!

platform :ios, '12.0'

target 'KhenshinSecureMessage_Example' do
  pod 'KhenshinSecureMessage', :path => '../'

  target 'KhenshinSecureMessage_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
